version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_container
    environment:
      POSTGRES_DB: TIA 
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@razdolbai.select
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pg_data/servers.db:/var/lib/pgadmin/pgadmin4.db
    depends_on:
      - postgres
volumes:
  postgres_data:

